name: 'Bunjy AI Analysis'
description: 'Perform AI-powered analysis on GitHub pull requests'
author: 'mohswell'
branding:
  icon: 'activity'
  color: 'blue'

inputs:
  base_app_url:
    description: 'Base URL for your AI analysis server'
    required: true
  api_key:
    description: 'API key for authentication'
    required: true

runs:
  using: "composite"
  steps:
    - name: Analyze PR
      shell: bash
      run: .github/workflows/scripts/analyze_files.sh
    - name: Send Metadata
      shell: bash
      run: .github/workflows/scripts/send_metadata.sh
    - name: Post Comment
      shell: bash
      run: .github/workflows/scripts/post_comment.sh
    - name: Process Feedback
      shell: bash
      run: .github/workflows/scripts/process_feedback.sh