name: 'Bunjy-AI'
description: 'Integrate AI into your code repository with an action powered by Gemini Nano'
author: 'mohswell'
branding:
  icon: 'activity'
  color: 'blue'

inputs:
  BASE_APP_URL:
    description: 'Base URL for the Nestjs web server making API calls to Gemini Nano models'
    required: true
  API_KEY:
    description: 'API key for authentication and authorization grants to Bunjy AI web resources'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}
 
    - name: Checkout workflow code
      uses: actions/checkout@v4
      with:
        repository: mohswell/mintify
        token: ${{ secrets.TOKEN }}
        path: 'reusable-actions'

    - name: Run the AI job
      shell: bash
      run: .github/workflows/ai.yml
