name: 'AI'
description: 'Integate AI to your code repository with an action powered by Gemini Nano'
author: 'mohswell'
branding:
  icon: 'activity'
  color: 'blue'

inputs:
  BASE_APP_URL:
    description: 'Base URL for the core server making API calls to Gemini'
    required: true
  API_KEY:
    description: 'API key for authentication and authorization'
    required: true

runs:
  using: "composite"
  steps:
    - name: Analyze PR
      shell: bash
      run: .github/workflows/scripts/analyze_files.sh
    - name: Send Metadata
      shell: bash
      run: .github/workflows/scripts/send_metadata.sh
    - name: Post Comment
      shell: bash
      run: .github/workflows/scripts/post_comment.sh
    - name: Process Feedback
      shell: bash
      run: .github/workflows/scripts/process_feedback.sh