name: 'Bunjy-AI'
description: 'Integrate AI into your code repository with an action powered by Gemini Nano'
author: 'mohswell'

inputs:
  BASE_APP_URL:
    description: 'Base URL for the Nestjs web server making API calls to Gemini Nano models'
    required: true
  API_KEY:
    description: 'API key for authentication and authorization grants to Bunjy AI web resources'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Prepare and run AI scripts
      shell: bash
      run: |
        # Print current directory and list contents for debugging
        pwd
        ls -R

        # Create scripts directory if it doesn't exist
        mkdir -p .github/workflows/scripts

        # Check if scripts exist
        if [ ! -d ".github/workflows/scripts" ]; then
          echo "Scripts directory does not exist"
          exit 1
        fi

        # Make scripts executable
        chmod +x .github/workflows/scripts/*.sh || true

        # Check if scripts are executable
        ls -l .github/workflows/scripts/*.sh

        # Run scripts
        .github/workflows/scripts/send_metadata.sh || echo "send_metadata.sh failed"
        .github/workflows/scripts/analyze_files.sh || echo "analyze_files.sh failed"
        .github/workflows/scripts/post_comment.sh || echo "post_comment.sh failed"
      env:
        BASE_APP_URL: ${{ inputs.BASE_APP_URL }}
        API_KEY: ${{ inputs.API_KEY }}
        GITHUB_TOKEN: ${{ github.token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}

branding:
  icon: 'activity'
  color: 'blue'