name: 'Bunjy-AI'
description: 'Integrate AI into your code repository with an action powered by Gemini Nano'
author: 'mohswell'

inputs:
  BASE_APP_URL:
    description: 'Base URL for the Nestjs web server making API calls to Gemini Nano models'
    required: true
  API_KEY:
    description: 'API key for authentication and authorization grants to Bunjy AI web resources'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run AI Analysis
      shell: bash
      run: |
        # Ensure scripts are executable
        chmod +x .github/workflows/scripts/*.sh
        
        # Run metadata send script
        .github/workflows/scripts/send_metadata.sh
        
        # Run file analysis script
        .github/workflows/scripts/analyze_files.sh
        
        # Run comment posting script
        .github/workflows/scripts/post_comment.sh
      env:
        BASE_APP_URL: ${{ inputs.BASE_APP_URL }}
        API_KEY: ${{ inputs.API_KEY }}
        GITHUB_TOKEN: ${{ github.token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}

branding:
  icon: 'activity'
  color: 'blue'