#!/usr/bin/env bash
set -e

echo "Posting comment on PR..."

COMMENT_BODY=$(cat << EOF
# Code Analysis Report

${ANALYSIS_RESULTS}

---

## Actions:
1. Review the analysis above
2. Choose an action:
   - Click [Approve](https://github.com/${REPO}/issues/${PR_NUMBER}/comments?body=/approve) to accept changes
   - Click [Reject](https://github.com/${REPO}/issues/${PR_NUMBER}/comments?body=/reject) to reject changes

## Test Generation:
After approving, you can:
- Reply \`/generate-tests\` to generate test cases
- Reply \`/skip-tests\` to skip test generation

*Generated by AI Code Analysis*
EOF
)

# Post the comment
curl -X POST \
  -H "Authorization: Bearer ${GITHUB_TOKEN}" \
  -H "Accept: application/vnd.github.v3+json" \
  -d "{\"body\": $(echo "$COMMENT_BODY" | jq -sR)}" \
  "https://api.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments"