#!/bin/bash

echo "Posting comment on PR..."
COMMENT_BODY=$(cat << EOF
# Code Analysis Report

${ANALYSIS_RESULTS}

---

- :white_check_mark: **[Approve](https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}/feedback?approve=true)**
- :x: **[Reject](https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}/feedback?approve=false)**

*Generated by AI Code Analysis*
EOF
)

curl -X POST \
  -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
  -H "Accept: application/vnd.github.v3+json" \
  -d "{\"body\": $(echo "$COMMENT_BODY" | jq -sR)}" \
  "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
