#!/usr/bin/env bash

echo "Posting comment on PR..."

COMMENT_BODY=$(cat << EOF
# Code Analysis Report

${ANALYSIS_RESULTS}

---

[Approve](https://github.com/${REPO}/issues/${PR_NUMBER}/comments?body=/approve) | [Reject](https://github.com/${REPO}/issues/${PR_NUMBER}/comments?body=/reject)

*Generated by AI Code Analysis*
EOF
)

# Post the comment
curl -X POST \
  -H "Authorization: Bearer ${GITHUB_TOKEN}" \
  -H "Accept: application/vnd.github.v3+json" \
  -d "{\"body\": $(echo "$COMMENT_BODY" | jq -sR)}" \
  "https://api.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments"
