name: Code Analysis
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write
  statuses: write
  contents: write
  issues: write

jobs:
  mintify_analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history
          ref: ${{ github.event.pull_request.head.sha }}  # Checkout PR branch
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up environment
        run: |
          echo "Setting up environment variables"
          echo "BASE_APP_URL=${{ secrets.BASE_APP_URL }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Get Changed Files
        id: changed_files
        run: |
          # Fetch all branches
          git fetch origin

          # Get the base branch (usually main or master)
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          
          # Get changed files between PR and base branch
          git diff --name-only --diff-filter=ACMRT origin/$BASE_BRANCH...HEAD > changed_files.txt
          
          echo "Changed files:"
          cat changed_files.txt


        - name: Test API Call
          run: |
            # Test the API call with a sample file
            sample_file="sample.js"
            echo "console.log('Hello, World!');" > $sample_file
            result=$(curl -X POST "${{ env.BASE_APP_URL }}/gemini/analyze-code" \
              -H "Authorization: Bearer ${{ env.API_KEY }}" \
              -H "Content-Type: application/json" \
              -d "$(jq -n --arg code "$(cat $sample_file)" '{code: $code}')")
            echo "API Response: $result"

     - name: Run Deep Analysis
        id: analyze_files
        run: |
          analysis_results=""
          cat changed_files.txt
          while IFS= read -r file; do
            if [[ "$file" == *.js || "$file" == *.ts ]]; then
              # Capture the analysis result
              echo "Analyzing file: $file"
              result=$(curl -X POST "${{ env.BASE_APP_URL }}/gemini/analyze-code" \
                -H "Authorization: Bearer ${{ env.API_KEY }}" \
                -H "Content-Type: application/json" \
                -d "$(jq -n --arg code "$(cat $file)" '{code: $code}')")
              echo "API Response: $result"
              analysis_results="$analysis_results\nFile: $file\n$result"
            fi
          done < changed_files.txt

          # Save the analysis results to be used in the comment
          echo "ANALYSIS_RESULTS<<EOF" >> $GITHUB_ENV
          echo "$analysis_results" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment on Pull Request with Analysis Results
        if: github.event.pull_request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use the GitHub API to post a comment on the pull request
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\": \"Code analysis results:\n${{ env.ANALYSIS_RESULTS }}\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"