name: Code Analysis

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  statuses: write
  contents: read
  issues: write

jobs:
  code_analysis:
    if: github.event_name != 'issue_comment'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up environment
        run: |
          echo "BASE_APP_URL=${{ secrets.BASE_APP_URL }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Get Changed Files
        id: changed_files
        run: |
          CHANGED_FILES=$(git diff --name-only "${{ github.event.pull_request.base.sha }}" "${{ github.event.pull_request.head.sha }}")
          FILTERED_FILES=$(echo "$CHANGED_FILES" | grep -E '\.(js|ts|yml|md)$' || true)
          ESCAPED_FILES=$(echo "$FILTERED_FILES" | jq -sR .)
          echo "files=$ESCAPED_FILES" >> $GITHUB_OUTPUT
      
      - name: Analyze Changed Files
        env:
          BASE_APP_URL: ${{ secrets.BASE_APP_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          CHANGED_FILES: ${{ steps.changed_files.outputs.files }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          bash .github/workflows/scripts/analyze_files.sh
        
      - name: Post Analysis Comment
        if: env.ANALYSIS_RESULTS != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          RUN_ID: ${{ github.run_id }}
        run: bash .github/workflows/scripts/post_comment.sh

  feedback_processing:
    needs: code_analysis
    if: github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Process Feedback and Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          BASE_APP_URL: ${{ secrets.BASE_APP_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          PR_NUMBER: ${{ github.event.issue.number }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: bash .github/workflows/scripts/feedback_and_tests.sh