name: Code Analysis

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write
  statuses: write
  contents: write
  issues: write

jobs:
  mintify_analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up environment
        run: bash .github/workflows/scripts/setup_env.sh

      - name: Analyze Files
        run: bash .github/workflows/scripts/analyze_files.sh

      - name: Post Analysis Comment
        run: bash .github/workflows/scripts/post_comment.sh

  handle_feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Listen for Feedback
        if: github.event.pull_request_review.state == 'approved' || github.event.pull_request_review.state == 'changes_requested'
        run: bash .github/workflows/scripts/handle_feedback.sh
