name: PR Analysis
on:
  workflow_dispatch:
  # pull_request:
  #   types: [opened, synchronize]
  #   branches:
  #     - '*'

permissions:
  contents: read
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up environment
        run: source ./scripts/api/config/env.sh

      - name: Analyze Code
        run: |
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.(js|ts|py|java)$'); do
            ./scripts/api/controllers/analyze_code.sh "$file"
          done
