name: Security Audit & Dependency Check

on:
  # push:
  #   branches:
  #     - main
  #     - development
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Run Security Audit
        run: npm audit --groups dependencies --severity critical || true